"""Updated User

Revision ID: c667313913f3
Revises: 026c0dce1a57
Create Date: 2024-04-30 22:04:12.080922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c667313913f3'
down_revision = '026c0dce1a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('reset_code_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_code_time')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
