"""Added loan purpose

Revision ID: dfd1942ed3a0
Revises: c667313913f3
Create Date: 2024-05-01 10:48:13.830412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd1942ed3a0'
down_revision = 'c667313913f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=250), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_code_time')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('reset_code_time', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
